export interface Service {
  id: string;
  slug: string;
  title: string;
  description: string;
  longDescription: string;
  outcome: string;
  metrics: string[];
  features: string[];
  benefits: string[];
  category: 'AI & Chatbots' | 'Automation' | 'Integration' | 'Data';
}

export const services: Service[] = [
  {
    id: '1',
    slug: 'ai-chatbot-development',
    title: 'AI Chatbot Development',
    category: 'AI & Chatbots',
    outcome: 'Customer Engagement',
    description: 'Advanced AI-powered conversational agents designed to handle complex queries and enhance user experience 24/7.',
    longDescription: 'Our AI Chatbot Development service leverages cutting-edge LLMs and NLP to create intelligent, context-aware assistants that seamlessly integrate with your existing platforms. From initial design to deployment, we build bots that learn and grow with your business, providing human-like interactions that drive satisfaction and reduce support overhead.',
    metrics: ['80% Query Resolution', 'Zero Wait Time', '24/7 Availability'],
    features: ['Natural Language Processing', 'Multi-Language Support', 'Sentiment Analysis', 'Contextual Memory'],
    benefits: ['Reduced Operational Costs', 'Improved Customer Retention', 'Scalable Support Infrastructure'],
  },
  {
    id: '2',
    slug: 'airtable-automation-services',
    title: 'Airtable Automation Services',
    category: 'Automation',
    outcome: 'Workflow Efficiency',
    description: 'Transform your Airtable bases into powerful, automated engines that synchronize data and trigger complex workflows.',
    longDescription: 'Airtable is more than just a spreadsheet; it\'s a foundation for your business operations. We build custom automations within and around Airtable to eliminate manual data entry, ensure data integrity, and connect your database to the rest of your tech stack via scripts and third-party integrations.',
    metrics: ['10+ Hours Saved/Week', 'Error-Free Sync', 'Zero Manual Entry'],
    features: ['Custom Scripting', 'Cross-Base Syncing', 'External API Triggers', 'Automated Reporting'],
    benefits: ['Centralized Data Truth', 'Real-Time Updates', 'Enhanced Team Collaboration'],
  },
  {
    id: '3',
    slug: 'b2b-leads-scrapping',
    title: 'B2B Leads Scraping',
    category: 'Data',
    outcome: 'Sales Pipeline',
    description: 'High-quality, targeted lead extraction from professional networks and directories to fuel your sales growth.',
    longDescription: 'Don\'t settle for outdated lead lists. Our B2B lead scraping services provide fresh, verified data points tailored to your specific ICP (Ideal Customer Profile). We utilize ethical and robust scraping technologies to gather contact info, company details, and social signals at scale.',
    metrics: ['High Conversion Rates', '98% Data Accuracy', 'Scalable Outreach'],
    features: ['LinkedIn Extraction', 'Verified Email Discovery', 'Firmographic Filtering', 'CRM Integration'],
    benefits: ['Full Sales Pipeline', 'Targeted Outreach', 'Reduced Prospecting Time'],
  },
  {
    id: '4',
    slug: 'custom-api-integration',
    title: 'Custom API Integration',
    category: 'Integration',
    outcome: 'System Synergy',
    description: 'Seamlessly connect disparate software systems with robust, secure, and high-performance custom API solutions.',
    longDescription: 'We specialize in bridge-building between your software tools. Our API integration services ensure that data flows smoothly between your CRM, ERP, and custom applications. We build custom middleware, handle complex mapping, and ensure your integrations are scalable and resilient.',
    metrics: ['Secure Data Flow', 'Low Latency Sync', 'Legacy System Support'],
    features: ['REST/GraphQL Implementation', 'Webhook Management', 'Authentication Protocols', 'Error Handling'],
    benefits: ['Eliminated Data Silos', 'Automated Synchronization', 'Enhanced System Capability'],
  },
  {
    id: '5',
    slug: 'discord-bot-development',
    title: 'Discord Bot Development',
    category: 'AI & Chatbots',
    outcome: 'Community Growth',
    description: 'Tailor-made Discord bots for automated moderation, community engagement, and custom utility features.',
    longDescription: 'Build a thriving community with a custom Discord bot. We develop bots that handle everything from complex onboarding and role management to interactive mini-games and external data integration (like crypto prices or stock updates).',
    metrics: ['Improved Retention', 'Automated Moderation', 'Interactive UX'],
    features: ['Slash Command Integration', 'Database Connectivity', 'OAuth2 Implementation', 'Real-time Alerts'],
    benefits: ['Managed Communities', 'Rich User Engagement', 'Branded Experience'],
  },
  {
    id: '6',
    slug: 'email-automation',
    title: 'Email Automation',
    category: 'Automation',
    outcome: 'Revenue Growth',
    description: 'Sophisticated email sequences that nurture leads, onboard customers, and drive conversions automatically.',
    longDescription: 'Maximize your ROI with personalized, trigger-based email campaigns. We design and implement complex automation flows that respond to user behavior in real-time, ensuring the right message reaches the right inbox at the perfect moment.',
    metrics: ['35% Open Rate Increase', 'High CTR', 'Automated Drip Feed'],
    features: ['Dynamic Personalization', 'A/B Testing Flows', 'Behavioral Triggers', 'Segmentation Engine'],
    benefits: ['Hands-free Marketing', 'Higher Conversion Rates', 'Consistent Brand Messaging'],
  },
  {
    id: '7',
    slug: 'google-sheet-automation',
    title: 'Google Sheet Automation',
    category: 'Automation',
    outcome: 'Data Management',
    description: 'Supercharge your spreadsheets with Apps Script and external integrations to build custom mini-applications.',
    longDescription: 'Turn your Google Sheets into powerful business tools. We go beyond basic formulas to implement complex Google Apps Script solutions that can call external APIs, generate documents, send emails, and process data automatically.',
    metrics: ['Reduced Human Error', 'Instant Data Sync', 'Custom Reporting'],
    features: ['Google Apps Script', 'Automated Form Processing', 'API Connectivity', 'Schedule Triggers'],
    benefits: ['Low-Cost Tools', 'Familiar Interface', 'Rapid Deployment'],
  },
  {
    id: '8',
    slug: 'hubspot-automation',
    title: 'Hubspot Automation',
    category: 'Automation',
    outcome: 'CRM Excellence',
    description: 'Maximize your HubSpot investment with advanced workflow automation and seamless third-party data sync.',
    longDescription: 'Unlock the full power of HubSpot. We build custom workflows that automate your sales pipe, marketing funnel, and service tickets. Whether it\'s complex lead scoring or custom object integration, we ensure HR is working for you, not vice versa.',
    metrics: ['Faster Deal Sprints', 'Clean CRM Data', 'Automated Nurture'],
    features: ['Complex Workflow Design', 'Custom Properties Sync', 'API Bridge Building', 'Sales Sequence Tuning'],
    benefits: ['Streamlined Sales', 'Better Lead Tracking', 'Data-Driven Insights'],
  },
  {
    id: '9',
    slug: 'make-com-automation',
    title: 'Make.com Automation Services',
    category: 'Automation',
    outcome: 'Process Operations',
    description: 'Visually complex and efficient automation scenarios using Make (formerly Integromat) to link 1000+ apps.',
    longDescription: 'When Zapier isn\'t enough, Make.com offers the granularity needed for complex logic. We design advanced scenarios with routers, iterators, and custom HTTP requests to build bulletproof business automations without the overhead of custom code.',
    metrics: ['Intricate Logic Support', 'Cost-Effective Scale', 'Detailed Error Logging'],
    features: ['Visual Workflow Design', 'Complex Data Mapping', 'Custom API Modules', 'Error Handling Steps'],
    benefits: ['Flexible Architecture', 'Scalable Operations', 'Rapid Prototyping'],
  },
  {
    id: '10',
    slug: 'n8n-google-sheets-automation',
    title: 'N8N Google Sheets Automation',
    category: 'Automation',
    outcome: 'Operational Independence',
    description: 'Self-hosted, highly technical n8n workflows that connect Google Sheets to your entire infrastructure.',
    longDescription: 'Leverage the power of open-source automation. n8n allows for unprecedented control and data privacy. We build custom nodes and workflows that treat Google Sheets as a dynamic database, syncing with internal tools and external APIs.',
    metrics: ['Data Privacy Focused', 'Unlimited Executions', 'Complex JS Integration'],
    features: ['Self-Hosted Setup', 'JavaScript Node Logic', 'Custom Webhooks', 'Database Connectors'],
    benefits: ['Reduced Subscription Costs', 'High Customizability', 'Secure Data Handling'],
  },
  {
    id: '11',
    slug: 'notion-integration',
    title: 'Notion Integration',
    category: 'Integration',
    outcome: 'Knowledge Management',
    description: 'Connect Notion to your tools to build automated dashboards, task trackers, and internal knowledge bases.',
    longDescription: 'Transform Notion from a simple note-taking app into your company\'s central operating system. We utilize the Notion API to sync data from CRMs, project management tools, and spreadsheets directly into your Notion databases.',
    metrics: ['Unified Dashboard', 'Real-time Project Sync', 'Auto-Populating Wikis'],
    features: ['Database API Sync', 'Custom Block Management', 'Automated Page Creation', 'Cross-Tool Mapping'],
    benefits: ['Tidy Workspace', 'Eliminated Context Switching', 'Live Project Visibility'],
  },
  {
    id: '12',
    slug: 'slackbot-development',
    title: 'Slackbot Development',
    category: 'AI & Chatbots',
    outcome: 'Team Productivity',
    description: 'Custom Slack bots to streamline internal communication, project management, and reporting.',
    longDescription: 'Bring your tools into your chat. We build custom Slack applications that allow your team to interact with your backend, trigger build scripts, report bugs, or even manage leave requests directly from a Slack message.',
    metrics: ['Faster Internal Feedback', 'Zero App Switching', 'Automated Reporting'],
    features: ['Interactive Modals', 'Slash Commands', 'Event Subscriptions', 'Block Kit UI'],
    benefits: ['Centralized Operations', 'High Team Adoption', 'Custom Built Workflows'],
  },
  {
    id: '13',
    slug: 'telegram-bot-development',
    title: 'Telegram Bot Development',
    category: 'AI & Chatbots',
    outcome: 'Mass Scaling',
    description: 'Fast, secure, and highly functional Telegram bots for broadcasting, community management, or crypto services.',
    longDescription: 'Telegram offers one of the most powerful bot APIs. We develop bots that can handle payments, provide real-time crypto alerts, manage massive groups, and offer a rich, app-like UI within the Telegram interface.',
    metrics: ['High Concurrency', 'Secure Payment Flow', 'Instant Alerts'],
    features: ['Inline Queries', 'Payment Gateway Integration', 'Bot API Customization', 'Encrypted Data Handling'],
    benefits: ['Global Reach', 'Secure Communications', 'Rapid Implementation'],
  },
  {
    id: '14',
    slug: 'whatsapp-chatbot-development',
    title: 'WhatsApp Chatbot',
    category: 'AI & Chatbots',
    outcome: 'Direct Customer Access',
    description: 'Meet your customers where they are with intelligent WhatsApp Business bots for sales and support.',
    longDescription: 'Maximize engagement on the world\'s most popular messaging app. We build WhatsApp chatbots using official APIs (Twilio, Gupshup, or Meta) to provide automated customer support, order tracking, and interactive product catalogs.',
    metrics: ['90+% Read Rate', 'Lower Acquisition Cost', 'Official API Verified'],
    features: ['Template Messages', 'AI NLP Integration', 'Interactive Buttons', 'Shared Inbox Support'],
    benefits: ['Frictionless UX', 'High Interaction Rates', 'Personalized Scaling'],
  },
  {
    id: '15',
    slug: 'zapier-automation',
    title: 'Zapier Automation',
    category: 'Automation',
    outcome: 'Rapid Connectivity',
    description: 'Quick and reliable connection of 5000+ apps to automate your most repetitive business tasks.',
    longDescription: 'Zapier is the gold standard for quick integrations. We help you design "Zaps" that are optimized for performance and reliability, using advanced features like filters, paths, and custom Python/JS code snippets where standard steps fall short.',
    metrics: ['No-Code Capability', 'Multi-Step Pathways', 'Immediate Deployment'],
    features: ['Complex Logic Paths', 'Custom Code Steps', 'Formatter Utilities', 'Webhook Triggers'],
    benefits: ['Agile Implementation', 'Reduced Human Tasks', 'Broad Ecosystem Support'],
  },
  {
    id: '16',
    slug: 'modern-ai-solutions',
    title: 'Modern AI Solutions',
    category: 'AI & Chatbots',
    outcome: 'Technological Edge',
    description: 'Custom AI implementations beyond simple chatbots, including RAG systems and autonomous agents.',
    longDescription: 'Stay ahead of the curve with customized AI solutions. We implement Retrieval-Augmented Generation (RAG) for localized knowledge bases, autonomous agents for multi-step task execution, and fine-tuned models for specific niche requirements.',
    metrics: ['Domain-Specific Intel', 'Auto-Task Execution', 'Enhanced Data ROI'],
    features: ['RAG Architectures', 'Vector Database Setup', 'Agentic Workflows', 'Model Fine-tuning'],
    benefits: ['Future-Proof Business', 'Intelligent Automation', 'Proprietary Knowledge ROI'],
  }
];
